language: julia
os:
    - linux
julia:
    - 0.5
    - nightly
notifications:
    email: false
after_success:
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("Tables")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("Tables")); using Coverage; Codecov.submit(Codecov.process_folder())'
