language: julia

os:
    - linux

julia:
    - 1.1

notifications:
    email: false

env:
  - JULIA_PROJECT="@."

after_success:
  - using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
